### ISSUE TITLE
Can't execute paid queries with the HashConnect Provider - No client operator is specified

### ISSUE THREAD

**Issue by ed-marquez** [Hashpack/hashconnect#111]
When trying either of the following paid queries with the HashPack provider or signer, 

```
const aInfo = await signer.getAccountInfo();
const bInfo = await provider.getAccountInfo(accountId);

```

The result is as follows:

```
Error: `client` must have an `operator` or an explicit payment transaction must be provided
    at AccountInfoQuery._beforeExecute (Query.js:228:1)
    at AccountInfoQuery.execute (Executable.js:375:1)
    at HashConnectSigner.getAccountInfo (signer.ts:54:1)
```

My understanding is that free queries can be executed by the provider's client directly without sending them to the wallet. However, for paid queries that's not the case. Paid queries (and txns) should be sent to the wallet. 
This is likely fixed by constructing the request using the account ID in the signer and passing that to the call method.

===============

For now, a workaround (not ideal) is passing the account ID and private key to the client operator in the provider. This requires hardcoding my private key in the application, which kinda defeats the purpose of the signer/provider architecture.

**Comment by teacoat** [comment]
We reccomend using mirror nodes for queries - we have no plans of allowing these paid queries through hashconnect
