### ISSUE TITLE
Error: No matching key. history: 1716990896575755 for AccountAllowanceApproveTransaction

### ISSUE THREAD

**Issue by apttx** [Hashpack/hashconnect#213]
hashconnect randomly just startet throwing errors for a transaction that was working fine before. the history key the error references changes on every attempt, but the error message is repeated 5+ times.

the transaction execution at https://github.com/blokk-studio/HLiquity/blob/b0a9a711d65c3d162366159f48b2ec063de8be08/packages/lib-hashgraph/src/HashgraphLiquity.ts#L2545 errors out immediately, even though hashpack shows me the approval dialog. the same for https://github.com/blokk-studio/HLiquity/blob/b0a9a711d65c3d162366159f48b2ec063de8be08/packages/lib-hashgraph/src/HashgraphLiquity.ts#L2564. using HashConnect.sendTransaction() results in the same. tried disconnect+reconnect, but the issue persists.

i don't have any repro steps, this started happening without any changes to my code.

- chrome: Version 124.0.6367.155 (Official Build) Arch Linux (64-bit)
- hashpack for chrome: 10.0.1
- hashconnect: 3.0.13
- @hashgraph/sdk: 2.41.0

![image](https://github.com/Hashpack/hashconnect/assets/62893352/4285720a-6b9b-4bd5-a45d-da19d15ebccd)
```
{context: 'client'} Error: No matching key. history: 1716991216393527
    at Vt.getRecord (index.js:148:1)
    at Vt.get (index.js:148:1)
    at ds2.onRelayEventResponse (index.js:148:1)
    at EventEmitter.<anonymous> (index.js:148:1)
LOG @ browser.js:202
(anonymous) @ browser.js:266
(anonymous) @ index.js:148
await in (anonymous) (async)
emit @ events.js:158
onMessageEvent @ index.js:148
await in onMessageEvent (async)
onProviderPayload @ index.js:148
await in onProviderPayload (async)
onPayloadHandler @ index.js:148
emit @ events.js:153
onPayload @ provider.ts:102
(anonymous) @ provider.ts:149
emit @ events.js:153
onPayload @ index.js:148
e.onmessage @ index.js:148
```
```
{context: 'client'}context: "client"[[Prototype]]: Object undefined
LOG @ browser.js:202
(anonymous) @ browser.js:266
Q3.request @ index.js:148
await in Q3.request (async)
DAppSigner2.request @ DAppSigner.js:49
(anonymous) @ signer.js:1
_0x50c9f6 @ signer.js:1
(anonymous) @ signer.js:1
(anonymous) @ signer.js:1
__awaiter2 @ signer.js:1
_0x25edd4.<computed>.<computed> @ signer.js:1
executeWithSigner @ Executable.js:501
approveHchfToSpendHchf @ HashgraphLiquity.ts:2547
await in approveHchfToSpendHchf (async)
(anonymous) @ StabilityDepositManager.tsx:166
call @ loading_state.ts:21
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```
![image](https://github.com/Hashpack/hashconnect/assets/62893352/40287e30-6a17-4cc0-862e-80c652bfca54)

**Comment by apttx** [comment]
restarting my browser fixed the issue. it's working again now

**Comment by apttx** [comment]
with hashpack 10.1.1, this error isn't caught and the transaction promise never resolves

```
Error: No matching key. history: 1717496949451525
    at Vt.getRecord (index.js:148:1)
    at Vt.get (index.js:148:1)
    at ds2.onRelayEventResponse (index.js:148:1)
    at EventEmitter.<anonymous> (index.js:148:1)
LOG @ browser.js:202
(anonymous) @ browser.js:266
(anonymous) @ index.js:148
await in (anonymous) (async)
emit @ events.js:158
onMessageEvent @ index.js:148
await in onMessageEvent (async)
onProviderPayload @ index.js:148
await in onProviderPayload (async)
onPayloadHandler @ index.js:148
emit @ events.js:153
onPayload @ provider.ts:102
(anonymous) @ provider.ts:149
emit @ events.js:153
onPayload @ index.js:148
e.onmessage @ index.js:148
browser.js:202 {context: 'client'} Error: No matching key. history: 1717496949451525
    at Vt.getRecord (index.js:148:1)
    at Vt.get (index.js:148:1)
    at ds2.onRelayEventResponse (index.js:148:1)
    at EventEmitter.<anonymous> (index.js:148:1)
LOG @ browser.js:202
(anonymous) @ browser.js:266
(anonymous) @ index.js:148
await in (anonymous) (async)
emit @ events.js:158
onMessageEvent @ index.js:148
await in onMessageEvent (async)
onProviderPayload @ index.js:148
await in onProviderPayload (async)
onPayloadHandler @ index.js:148
emit @ events.js:153
onPayload @ provider.ts:102
(anonymous) @ provider.ts:149
emit @ events.js:153
onPayload @ index.js:148
e.onmessage @ index.js:148
2index.js:148 Uncaught (in promise) Error: No matching key. history: 1717496949451525
    at Vt.getRecord (index.js:148:1)
    at Vt.get (index.js:148:1)
    at Br2.onRelayEventResponse (index.js:148:1)
    at EventEmitter.<anonymous> (index.js:148:1)
```

![image](https://github.com/Hashpack/hashconnect/assets/62893352/24a121a1-02eb-4d66-8f7f-38af28d688e7)

**Comment by apttx** [comment]
actually, the error is caught, but what i get is an empty error. it's also broken until i restart my browser agai. still hashpack 10.1.1

![image](https://github.com/Hashpack/hashconnect/assets/62893352/57cd62d8-7eb0-4623-a195-eecf1a0b0be6)
```ts
try {
  // ...
} catch (throwable) {
  console.debug({ throwable })
}
```
![image](https://github.com/Hashpack/hashconnect/assets/62893352/cbb471bf-b517-4e19-8dd0-2654517b726a)

**Comment by apttx** [comment]
i guess there might be some stringification going on somewhere
![image](https://github.com/Hashpack/hashconnect/assets/62893352/290f15c8-ed53-4a20-a11a-948849ea2ced)

**Comment by phucvarmeta** [comment]
Any updates ?
