### ISSUE TITLE
It does not work with Svelte (and Rollup.js)

### ISSUE THREAD

**Issue by srokatonie** [Hashpack/hashconnect#32]
Hi, it does not work with Svelte default build settings. I know you build your example using Angular. I am wondering if somebody could try use React with the library?

```
> svelte-app@1.0.0 dev /Users/magic/Dev/_svelte/hashconnect-test
> rollup -c -w

rollup v2.61.1
bundles src/main.js → public/build/bundle.js...
(!) Plugin node-resolve: preferring built-in module 'buffer' over local alternative at '/Users/magic/Dev/_svelte/hashconnect-test/node_modules/buffer/index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'events' over local alternative at '/Users/magic/Dev/_svelte/hashconnect-test/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/js-waku/build/esm/lib/discovery.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence
node_modules/js-waku/build/esm/lib/waku.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence
node_modules/js-waku/build/esm/lib/waku_message/version_1.js
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 1 other occurrence

...and 6 other files
(!) Circular dependencies
node_modules/protobufjs/src/util/minimal.js -> node_modules/protobufjs/src/util/longbits.js -> node_modules/protobufjs/src/util/minimal.js
node_modules/protobufjs/src/util/minimal.js -> node_modules/protobufjs/src/util/longbits.js -> /Users/magic/Dev/_svelte/hashconnect-test/node_modules/protobufjs/src/util/minimal.js?commonjs-proxy -> node_modules/protobufjs/src/util/minimal.js
node_modules/js-waku/build/esm/lib/waku.js -> node_modules/js-waku/build/esm/lib/waku_light_push/index.js -> node_modules/js-waku/build/esm/lib/waku.js
...and 6 more
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
tslib (imported by tslib?commonjs-external)
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules/@protobufjs/inquire/index.js
10: function inquire(moduleName) {
11:     try {
12:         var mod = eval("quire".replace(/^/,"re"))(moduleName); // eslint-disable-line no-eval
                      ^
13:         if (mod && (mod.length || Object.keys(mod).length))
14:             return mod;
[!] Error: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
https://rollupjs.org/guide/en/#outputformat
Error: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
    at error (/Users/magic/Dev/_svelte/hashconnect-test/node_modules/rollup/dist/shared/rollup.js:158:30)
    at validateOptionsForMultiChunkOutput (/Users/magic/Dev/_svelte/hashconnect-test/node_modules/rollup/dist/shared/rollup.js:16090:16)
    at Bundle.generate (/Users/magic/Dev/_svelte/hashconnect-test/node_modules/rollup/dist/shared/rollup.js:15929:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at handleGenerateWrite (/Users/magic/Dev/_svelte/hashconnect-test/node_modules/rollup/dist/shared/rollup.js:23464:23)
    at async Promise.all (index 0)
    at Task.run (/Users/magic/Dev/_svelte/hashconnect-test/node_modules/rollup/dist/shared/watch.js:243:32)
    at Watcher.run (/Users/magic/Dev/_svelte/hashconnect-test/node_modules/rollup/dist/shared/watch.js:170:13)
```

Check this repo to reproduce [https://github.com/srokatonie/hashconnect-test](https://github.com/srokatonie/hashconnect-test)
```
npm install
npm run dev
```

You can try to avoid some errors in the console by amending `rollup.config.js`
```
output: {
§sourcemap: true,
name: 'app',
inlineDynamicImports: true, // <- uncomment this
format: 'iife',
file: 'public/build/bundle.js',
},
```
But then you are getting error in browser's console:

```
node.js:36 Uncaught ReferenceError: tslib_1 is not defined
    at node.js:36
```
<img width="603" alt="Screenshot 2021-12-23 at 17 25 50" src="https://user-images.githubusercontent.com/12460055/147267493-7377eab6-9ad7-441b-890d-c9e4622d046b.png">

I spend some time on Rollup settings but unfortunately I could not resolve. Angular uses Webpack as build tool, which can be applied in Svelte and possibly resolve the issue. However, this doesn't work "out of the box".

**Comment by srokatonie** [comment]
I finally managed to get it working, example repo: https://github.com/srokatonie/hashconnect-webpack
